[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gridmaker"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "mpi4py",
    "dill",
    "numpy",
    "tqdm",
    "scipy",
    "h5py",
]
